spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: face
  profiles:
    include: aws

capture:
  save:
    path: /home/ec2-user/captures
