spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: face
  profiles:
    include: aws, picture

capture:
  save:
    path: /home/ec2-user/captures
